### ISSUE TITLE
Very raw yet, but interesting!

### ISSUE THREAD

**Issue by i-panov** [MatthewPattell/yii2-di-magic#1]
The idea is interesting, but there is not enough documentation. In what section of the configuration to enter these settings? What class them to point fingers? Without specifying a component or module class, there will be an error immediately. Tried to specify the DIClassBuilder class, but it didn't work. The error does not fall, but an empty model is passed to the method.

Very raw. I'd love to use it if you could work it out.

**Comment by MatthewPattell** [comment]
@i-panov ok, add your configuration container like below:
_in common/config/main.php or in other app (e.g. backend/config/main.php)_
```
return [
    'id' => 'app-common',
    'components' => [
         // your components... 
    ],
    'container'           => [
        'definitions' => [
            YourActiveRecordClass::class => DIClassBuilder::bind(),
        ],
    ],
];
```

**Comment by i-panov** [comment]
@MatthewPattell Rather strange. Usually these things are placed in components or modules. Now it works. Thanks.

**Comment by i-panov** [comment]
@MatthewPattell Is there a way to get an empty model into a method instead of a 404 error?

**Comment by MatthewPattell** [comment]
@i-panov example:
```
    /**
     * Sample action.
     *
     * @param  ARModel|NULL $model not required
     *
     * @return void
     */
    public function actionSample(ARModel $model = NULL): void
    {        
        if (is_null($model)) {
            // 
        }
    }
```

**Comment by i-panov** [comment]
@MatthewPattell It's not exactly what I was asking, but if there's no other way, fine.
